[build]
  command = "dotnet publish -c Release -o ./publish"
  publish = "publish"

[build.environment]
  DOTNET_CORE_VERSION = "6.0"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"
  DOTNET_CLI_TELEMETRY_OPTOUT = "true"
